name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # checkout code
    - name: checkout code
      uses: actions/checkout@v2

    - name: set directory
      run: cd $GITHUB_WORKSPACE

    - name: python set up
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.4'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q